name: CI

on:
  push:
    branches: [main]
  pull_request:

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6

      - name: Setup Aqua
        uses: aquaproj/aqua-installer@v4.0.4
        with:
          aqua_version: v2.59.0

      - uses: actions/setup-go@v6
        id: setup-go
        with:
          go-version-file: go.mod
          cache: false

      - uses: actions/cache@v5
        with:
          path: |
            ~/.cache/go-build
            ~/.go/pkg/mod
          key: go-${{ runner.os }}-${{ steps.setup-go.outputs.go-version }}-${{ hashFiles('go.sum') }}
          restore-keys: |
            go-${{ runner.os }}-${{ steps.setup-go.outputs.go-version }}-

      - name: Go mod download
        run: go mod download

      - name: Run tests
        run: go test -race -cover ./...

  lint:
    name: Lint
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pull-requests: read
    steps:
      - uses: actions/checkout@v6

      - name: Setup Aqua
        uses: aquaproj/aqua-installer@v4.0.4
        with:
          aqua_version: v2.59.0

      - uses: actions/setup-go@v6
        id: setup-go
        with:
          go-version-file: go.mod
          cache: false

      - uses: actions/cache@v5
        with:
          path: |
            ~/.cache/go-build
            ~/.go/pkg/mod
          key: go-${{ runner.os }}-${{ steps.setup-go.outputs.go-version }}-${{ hashFiles('go.sum') }}-lint
          restore-keys: |
            go-${{ runner.os }}-${{ steps.setup-go.outputs.go-version }}-

      - name: Go mod download
        run: go mod download

      - name: Run golangci-lint
        uses: golangci/golangci-lint-action@v9
        with:
          install-mode: none
